# Generated by Django 4.0.4 on 2022-04-13 11:45

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_showroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default=None, null=True)),
                ('percent', core.fields.PositiveDecimalField(decimal_places=2, default=5, max_digits=5)),
                ('end_date', models.DateField(blank=True)),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_showroom.car')),
                ('suppliers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='car_showroom.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarShowroomSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default=None, null=True)),
                ('percent', core.fields.PositiveDecimalField(decimal_places=2, default=5, max_digits=5)),
                ('end_date', models.DateField(blank=True)),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_showroom.car')),
                ('showrooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='car_showroom.carshowroom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
