# Generated by Django 4.0.4 on 2022-04-13 11:45

import core.fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('max_speed', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('engine', models.CharField(max_length=50)),
                ('engine_power', models.PositiveIntegerField(default=0)),
                ('mileage', models.FloatField(default=0)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='white', max_length=20)),
                ('type', models.CharField(default='sedan', max_length=20)),
                ('year', models.IntegerField(blank=True, validators=[core.validators.year_validator])),
                ('image', models.URLField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarShowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('location', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('balance', core.fields.PositiveDecimalField(decimal_places=2, max_digits=5)),
                ('buy_query', models.JSONField(blank=True, default={'color': 'white', 'engine_power': 0, 'max_speed': 0, 'name': None, 'type': 'sedan'})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('age', models.PositiveIntegerField(blank=True)),
                ('balance', core.fields.PositiveDecimalField(decimal_places=2, max_digits=5)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('date_of_creation', models.DateField(blank=True)),
                ('number_of_buyers', models.PositiveIntegerField(default=0)),
                ('location', django_countries.fields.CountryField(blank=True, max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', core.fields.PositiveDecimalField(decimal_places=2, max_digits=5)),
                ('count', models.PositiveIntegerField(default=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_showroom.car')),
                ('car_showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_showroom.carshowroom')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_showroom.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierSellCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', core.fields.PositiveDecimalField(decimal_places=2, max_digits=5)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_showroom.car')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_showroom.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='cars',
            field=models.ManyToManyField(through='car_showroom.SupplierSellCar', to='car_showroom.car'),
        ),
        migrations.CreateModel(
            name='ShowroomSellCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('price', core.fields.PositiveDecimalField(decimal_places=2, max_digits=5)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_showroom.car')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_showroom.carshowroom')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_showroom.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='transactions',
            field=models.ManyToManyField(through='car_showroom.Transaction', to='car_showroom.car'),
        ),
        migrations.AddField(
            model_name='carshowroom',
            name='cars',
            field=models.ManyToManyField(through='car_showroom.ShowroomSellCar', to='car_showroom.car'),
        ),
    ]
