version: '3.8'

services:
  db:
    image: postgres:14
    container_name: database_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  web:
    build: .
    command: sh ./web.sh
    container_name: django
    volumes:
      - .:/showroom
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: