version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=showroom

  web:
    build: .
    command: sh ./web.sh
    volumes:
      - .:/docker
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: